name: Generate Blog Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.1'
      
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Create 'html_output' Folder
        run: mkdir -p html_output

      - name: Convert Notebooks to HTML
        run: |
          mkdir html_outputs
          for notebook in *.ipynb; do
            jupyter nbconvert --to html $notebook --output-dir html_outputs
          done
