name: Generate Blog Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger

permissions:
  contents: write
  #pages: write

jobs:
  convert-to-html:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.1'
      
      - name: Install Dependencies
        run: |
          pip install nbconvert

      - name: Convert Notebooks to HTML
        run: |
          mkdir -p docs
          for notebook in *.ipynb; do
            jupyter nbconvert --to html $notebook --output-dir docs
          done

      - name: Generate Index HTML
        run: |
          python generate_index.py

      - name: Commit and Push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git checkout --orphan gh-pages
          git rm -rf .
          cp -r docs/* .
          git add .
          git commit -m "Deploy HTML files"
          git push origin gh-pages --force
    
