name: Test Notebooks
on:
  schedule:
    - cron: '0 5 * * *'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.1'
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Test Notebooks
      run: pytest --nbval-lax
