name: Test Notebooks
on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:  # Allows manual trigger
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.1'
    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
    - name: Create 'output' Folder
      run: mkdir -p output
    - name: Install FFmpeg
      run: sudo apt-get install -y ffmpeg
    - name: Test Notebooks
      env: 
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: pytest --nbval-lax
